### ISSUE TITLE
Improper indices array allocation

### ISSUE THREAD

**Issue by iOrange** [Rinnegatamante/vitaQuakeIII#11]
Hi!

I was browsing the source code as a start point to wet my feet in PSVita coding, and I came across this line:
https://github.com/Rinnegatamante/vitaQuakeIII/blob/5365237156782c6bf9dde519a88799ce85780dc1/code/psp2/psp2_glimp.c#L141

From what I understand - the intention is to have an array of uint16_t, but on allocation we actually allocate an array of a bigger size  (uint16_t*  is a pointer and thus will take more space than uint16_t).

Not a critical issue though.

Thanks for your work!

**Comment by Rinnegatamante** [comment]
https://github.com/Rinnegatamante/vitaQuakeIII/commit/973173206e1f4aa5c3048bf8428feab3b10bd5df fixes this.

**Comment by iOrange** [comment]
Wow that was fast, thanks!
