### ISSUE TITLE
S_WriteLinearBlastStereo16 issue

### ISSUE THREAD

**Issue by Qiyamah** [Rinnegatamante/vitaQuakeIII#12]
Executing (target): make
make[1]: Entering directory '/home/rra/Lakka-LibreELEC/build.Lakka-Generic.i386-2.3-devel/vitaquake3-bee3d54'
LD vitaquake3_libretro.so
/tmp/vitaquake3_libretro.so.nMJqL9.ltrans8.ltrans.o:<artificial>:function S_Base_Update: error: undefined reference to 'S_WriteLinearBlastStereo16'
collect2: error: ld returned 1 exit status
make[1]: *** [Makefile:207: vitaquake3_libretro.so] Error 1
make[1]: Leaving directory '/home/rra/Lakka-LibreELEC/build.Lakka-Generic.i386-2.3-devel/vitaquake3-bee3d54'
Makefile:29: recipe for target 'image' failed
make: *** [image] Error 2

**Comment by Rinnegatamante** [comment]
This is not the libretro related repo. Please post those issues here: https://github.com/libretro/vitaquake3
