### ISSUE TITLE
 Q_ftol lrintf issue

### ISSUE THREAD

**Issue by Qiyamah** [Rinnegatamante/vitaQuakeIII#13]
In file included from code/qcommon/common.c:24:
code/qcommon/q_shared.h:461:18: error: 'lrintf' redeclared as different kind of symbol
  461 |   #define Q_ftol lrintf

**Comment by Rinnegatamante** [comment]
Ditto https://github.com/Rinnegatamante/vitaQuakeIII/issues/12
