### ISSUE TITLE
Doesn't recognize folder structure

### ISSUE THREAD

**Issue by aknight2015** [Rinnegatamante/vitaQuakeIII#15]
I'm putting the baseq3 directory from the full version of Quake 3 Arena in the ioq3 directory. I start up the game and it says that it can't find the files and downloads the shareware version. It ends up overwritting the full version files as it goes to the same directory.

https://imgur.com/gallery/Kq6uyu5

**Comment by Rinnegatamante** [comment]
you need to first download shareware files via the download and then overwrite existing ones with full data.
