### ISSUE TITLE
Unable to build with makefile Makefile.oa

### ISSUE THREAD

**Issue by mrdude2478** [Rinnegatamante/vitaQuakeIII#18]
As per the title, I can build fine the standard makefile, but Quake3 OA doesn't work with that. It does work with team arena and quake 3 though.

I am using the latest vitaGL and have tried commit versions from december 2022 up until the latest, but when using: make -f makefile.oa I get this error:

```
/arm-vita-eabi/13.1.0/../../../../arm-vita-eabi/lib\libvitashark.a(vitashark.o): in function `shark_init':
C:\msys64\home\MrDude\vita\vitashark/source/vitashark.c:65: undefined reference to `sceShaccCgExtEnableExtensions'
C:/msys64/usr/local/vitasdk/bin/../lib/gcc/arm-vita-eabi/13.1.0/../../../../arm-vita-eabi/bin/ld.exe: C:/msys64/usr/local/vitasdk/bin/../lib/gcc
/arm-vita-eabi/13.1.0/../../../../arm-vita-eabi/lib\libvitashark.a(vitashark.o): in function `shark_end':
C:\msys64\home\MrDude\vita\vitashark/source/vitashark.c:81: undefined reference to `sceShaccCgExtDisableExtensions'
collect2.exe: error: ld returned 1 exit status
make: *** [makefile.oa:42: openarena.elf] Error 1
```

undefined reference to `sceShaccCgExtDisableExtensions' - do I need to install something to build this?

PS I am using the latest vitaGL, vpdm, and I've compiled and installed this:
vitaShaRK + this: https://github.com/bythos14/SceShaccCgExt.git

**Comment by Rinnegatamante** [comment]
Add SceShaccCgExt in the libs list.

**Comment by mrdude2478** [comment]
Thanks, that worked I also needed to add "-ltaihen_stub" to makefile.oa, after that everything built fine.

Also there's an issue with vitaGL textures since commit 1334255cc6 (March 29), that commit messes up the graphics in the maps, I reverted the changes made in that commit on the latest version and that fixes the textures again.

**Comment by Rinnegatamante** [comment]
Should be now fixed.
