### ISSUE TITLE
Q3TOURNEY6 - Double Mirror causes weird graphical errors

### ISSUE THREAD

**Issue by Sarkie** [Rinnegatamante/vitaQuakeIII#19]
https://www.youtube.com/watch?v=JDWoszMb1Kg

This is what it's meant to look like
![image](https://github.com/Rinnegatamante/vitaQuakeIII/assets/283203/c047c8be-1a79-41cb-8179-c7d06d2c3e38)

But on the Vita, it looks to get into a warping effect, wasn't sure if Q3 or VitaGL issue.

![image](https://github.com/Rinnegatamante/vitaQuakeIII/assets/283203/b6260998-5c48-4b63-bd38-24a175059646)

**Comment by Rinnegatamante** [comment]
Is this happening only on last build or was it happening prior as well?

**Comment by Sarkie** [comment]
It was happening prior, sorry forgot to mention that.
Was waiting for the latest VitaGL to be updated to make sure it wasn't that.

**Comment by Rinnegatamante** [comment]
Same issue is present also on portals or mirrors by any chance?

**Comment by Sarkie** [comment]
@Rinnegatamante 
Actually, just checked, same issue occurs on the very first mirror, on the first level and the portal shows it, but not as bad due to foggy textures.

Map = q3dmo.bsp

**Comment by Rinnegatamante** [comment]
@Sarkie Can you pick me screenshots for the first mirror and the portal?

(Asking cause that's how it looks on current build i'm adjusting for a release and don't know if it's indeed fixed)
![image](https://github.com/user-attachments/assets/55ebe5ab-a974-4367-a242-348617da812f)
![image](https://github.com/user-attachments/assets/55347490-5f07-4862-8650-e0d2f29c2a76)
![immagine](https://github.com/user-attachments/assets/b4d3bcfb-6b05-4893-8c85-e5cc3a97d2d5)

**Comment by Rinnegatamante** [comment]
Also, doublecheck that you don't have `seta r_noportals "1"` in your q3config.cfg.

**Comment by Sarkie** [comment]
Will do @Rinnegatamante get back to later tonight

**Comment by Sarkie** [comment]
> Also, doublecheck that you don't have `seta r_noportals "1"` in your q3config.cfg.

This wasn't set, but setting it manually to "0" at the bottom of the file seems to have fixed it for me.

Not sure how it decides not to enable them.

Thanks
