### ISSUE TITLE
Players invisible in 67's demo type

### ISSUE THREAD

**Issue by stranno** [Rinnegatamante/vitaQuakeIII#2]
68's demo version included with ioq3 seems to work fine but in this 67's demo the opponent is invisible.

![gif](https://user-images.githubusercontent.com/6293197/37555130-ea324372-29e2-11e8-89f2-77f43f8cadc1.gif)

**Comment by Rinnegatamante** [comment]
Have only a demo on my installation so can't say for sure what is. May be an out of RAM when loading textures. (Usually when happens, during map loading you won't see even the icon for the model that will not be rendered in game)

**Comment by stranno** [comment]
You need to add this demo to the pak8 file, inside demos folder (where the ioq3 default demo is located). It is supposed to be a 67 demo (pak7) but it doesnt show this way in the demo menu. Maybe thats the problem, packing a 67 demo inside pak8.

[fatality.zip](https://github.com/Rinnegatamante/vitaQuakeIII/files/1821600/fatality.zip)

**Comment by Rinnegatamante** [comment]
This should be fixed in public release, waiting for an updated statement on the issue.
