### ISSUE TITLE
Q3TOURNEY1 lightning broken

### ISSUE THREAD

**Issue by stranno** [Rinnegatamante/vitaQuakeIII#3]
In this level the lightning seems to be broken, with a white layer covering the screen in areas with lights on the walls. It gets fixed temporarily when you shoot a weapon.

![gif](https://user-images.githubusercontent.com/6293197/37555157-624fb466-29e3-11e8-81d1-99860d31ae4b.gif)

**Comment by Rinnegatamante** [comment]
It depends on your config file.

**Comment by stranno** [comment]
It is a vanilla config file, i belive i only changed 3D models for icons.

**Comment by Rinnegatamante** [comment]
Disable dynamic lights. They're broken and produce only bad effects.

**Comment by Rinnegatamante** [comment]
Seems not to be related to dynamic lights. Investigating the issue.

**Comment by Rinnegatamante** [comment]
Fixed with https://github.com/Rinnegatamante/vitaQuakeIII/commit/3cff7e6090275fd85e8e96d60871ed75802ba9c4
