### ISSUE TITLE
complete one map

### ISSUE THREAD

**Issue by Myst0z** [Rinnegatamante/vitaQuakeIII#4]
![20180323_130543](https://user-images.githubusercontent.com/37696775/37828759-cb96f6d8-2e9c-11e8-80de-d92fe0614b7d.jpg)

**Comment by Ch3lin** [comment]
that happened to me when at the end of a game you precionas Menu instead of Next..

**Comment by Rinnegatamante** [comment]
You're not using shared libraries (aka .suprx files provided with Data Files).
