### ISSUE TITLE
Error trying to load Team arena

### ISSUE THREAD

**Issue by Ch3lin** [Rinnegatamante/vitaQuakeIII#5]
Touching the live area icon throws me this error and Team Arena does not load. Can you help me? Thank you.
![whatsapp image 2018-03-23 at 10 24 30 am](https://user-images.githubusercontent.com/36119214/37831578-ccbb1372-2e84-11e8-8576-f46aa7c40026.jpeg)

**Comment by Rinnegatamante** [comment]
https://www.reddit.com/r/vitahacks/comments/86btna/release_vitaquakeiii_v05_beta_quake_iii_quake_iii/dw4yay2/

**Comment by Ch3lin** [comment]
Work Now. Thaks :D
