### ISSUE TITLE
add support of 1280x720 resolution for PS TV

### ISSUE THREAD

**Issue by greggameplayer** [Rinnegatamante/vitaQuakeIII#6]
is there for you to add the compatibility for 1280x720 resolution in order to have better graphics on PS TV.
I think in order to run this game with this resolution it will require overclock of the GPU and CPU in order to run it at full speed.
But it will be a great add for those who have the PS TV.

**Comment by Rinnegatamante** [comment]
PSTV can't render at resolutions higher than PSVita.
