### ISSUE TITLE
texture layering issue

### ISSUE THREAD

**Issue by eiiiiix** [Rinnegatamante/vitaQuakeIII#7]
ive noticed that some textures in the ui appear behind certain terrains entities and weapons
dont remember this on pc so im not sure if its an issue or not

**Comment by Rinnegatamante** [comment]
It is.

**Comment by Rinnegatamante** [comment]
Fixed with https://github.com/Rinnegatamante/vitaGL/commit/6b4e665c0511710d590b116330eda9889f1d2903
